# Generated by Django 6.0.6 on 2026-08-26 12:31

import django.db.models.deletion
import django.utils.timezone
import scholarships.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_session', models.CharField(help_text='e.g. 2024/2025', max_length=20, verbose_name='Academic Session')),
                ('institution', models.CharField(max_length=255, verbose_name='Institution / University')),
                ('course_of_study', models.CharField(max_length=255, verbose_name='Course of Study')),
                ('level', models.CharField(help_text='e.g. 100 Level, 200 Level, MSc Year 1', max_length=50, verbose_name='Current Level')),
                ('current_cgpa', models.DecimalField(decimal_places=2, help_text='On a 5.0 or 4.0 scale — specify scale in your statement.', max_digits=4, verbose_name='Current CGPA / GPA')),
                ('statement_of_purpose', models.TextField(help_text='Explain why you need this scholarship and your academic goals.', verbose_name='Statement of Purpose')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20, verbose_name='Application Status')),
                ('reviewer_notes', models.TextField(blank=True, help_text='Internal notes from the reviewer. Not shown to applicant.', verbose_name='Reviewer Notes')),
                ('application_date', models.DateField(default=django.utils.timezone.now, verbose_name='Application Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_applications', to=settings.AUTH_USER_MODEL, verbose_name='Applicant')),
            ],
            options={
                'verbose_name': 'Scholarship Application',
                'verbose_name_plural': 'Scholarship Applications',
                'ordering': ['-application_date', '-created_at'],
                'unique_together': {('applicant', 'academic_session')},
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('admission_letter', 'Admission / Acceptance Letter'), ('school_id', 'School ID Card'), ('result', 'Academic Result / Transcript'), ('other', 'Other Supporting Document')], default='other', max_length=30, verbose_name='Document Type')),
                ('file', models.FileField(help_text='PDF, JPG, or PNG — max 5 MB.', upload_to=scholarships.models.document_upload_path, validators=[scholarships.models.validate_document_file], verbose_name='File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='scholarships.scholarshipapplication', verbose_name='Application')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['document_type', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_date', models.DateField(verbose_name='Award Date')),
                ('amount_awarded', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount Awarded (₦)')),
                ('notes', models.TextField(blank=True, verbose_name='Award Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_record', to='scholarships.scholarshipapplication', verbose_name='Application')),
            ],
            options={
                'verbose_name': 'Scholarship Recipient',
                'verbose_name_plural': 'Scholarship Recipients',
                'ordering': ['-awarded_date'],
            },
        ),
    ]
