# Generated by Django 6.0.6 on 2026-09-08 08:40

import scholarships.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='scholarship_docs/birth_certs/', validators=[scholarships.models.validate_document_file], verbose_name='Birth Certificate'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='is_submitted',
            field=models.BooleanField(default=False, verbose_name='Final Submission Locked'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='scholarship_docs/passports/', verbose_name='Passport Photograph'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='school_letter',
            field=models.FileField(blank=True, null=True, upload_to='scholarship_docs/school_letters/', validators=[scholarships.models.validate_document_file], verbose_name='Official School Letter'),
        ),
    ]
