# Generated by Django 6.0.6 on 2026-09-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_scholarshipapplication_birth_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='member_recommendation',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Recommended', 'Recommended'), ('Not Recommended', 'Not Recommended')], default='Pending', max_length=50, verbose_name='Member Recommendation'),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('recommended', 'Recommended'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20, verbose_name='Application Status'),
        ),
    ]
