# Generated by Django 6.0.6 on 2026-09-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0003_scholarshipapplication_member_recommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='account_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
