# Generated by Django 6.0.6 on 2026-09-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0004_scholarshipapplication_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='disbursement_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='is_disbursed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('recommended', 'Recommended'), ('accepted', 'Accepted'), ('screening_passed', 'Screening Passed'), ('awarded', 'Awarded'), ('disbursed', 'Disbursed'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20, verbose_name='Application Status'),
        ),
    ]
