"""
core/management/commands/seed_demo_data.py

Phase 5: Demo Seeder.
Populates the KB Foundation database with realistic dummy data for 
Donors, Donations, Expenditures, and Scholarships. 
"""

import random
from datetime import timedelta
from decimal import Decimal
from django.core.management.base import BaseCommand
from django.utils import timezone
from faker import Faker

from accounts.models import CustomUser
from donors.models import Donor, Donation
from expenditures.models import Expenditure
from scholarships.models import ScholarshipApplication, ScholarshipRecipient


class Command(BaseCommand):
    help = 'Seeds the database with realistic demo data for stakeholder presentation.'

    def handle(self, *args, **options):
        # 1. Safety Check
        if Donor.objects.count() > 5 or Expenditure.objects.count() > 5:
            self.stdout.write(self.style.WARNING(
                '[WARN] Database already contains significant data. Aborting seed to prevent duplication.'
            ))
            return

        fake = Faker('en_NG')  # Realistic Nigerian names/addresses if available, fallback otherwise.

        self.stdout.write('[INFO] Starting database seed...')
        now = timezone.now()

        # ---------------------------------------------------------------------
        # 1. Create Fake Donors (15)
        # ---------------------------------------------------------------------
        donors = []
        for i in range(15):
            first = fake.first_name()
            last = fake.last_name()
            email = f"demo_donor_{i}_{fake.email()}"

            # Create CustomUser for Donor
            user = CustomUser.objects.create_user(
                username=email,
                email=email,
                password='Password123!',
                first_name=first,
                last_name=last,
                role=CustomUser.Role.DONOR,
                requires_password_change=True
            )

            donor = Donor.objects.create(
                user=user,
                full_name=f"{first} {last}",
                email=email,
                phone=fake.phone_number()[:20],
                address=fake.address(),
                notes="Generated by Demo Seeder."
            )
            donors.append(donor)

        self.stdout.write(self.style.SUCCESS(f'[OK] Created {len(donors)} Fake Donors.'))

        # ---------------------------------------------------------------------
        # 2. Create Fake Donations (40)
        # ---------------------------------------------------------------------
        methods = [m[0] for m in Donation.PaymentMethod.choices]
        for _ in range(40):
            donor = random.choice(donors)
            days_ago = random.randint(1, 365)
            donation_date = (now - timedelta(days=days_ago)).date()
            amount = round(random.uniform(5000, 500000), 2)

            rand_status = random.random()
            if rand_status < 0.15:
                status = Donation.Status.PENDING
            elif rand_status < 0.25:
                status = Donation.Status.REJECTED
            else:
                status = Donation.Status.CONFIRMED

            donation = Donation(
                donor=donor,
                amount=amount,
                date=donation_date,
                payment_method=random.choice(methods),
                reference_number=fake.uuid4()[:12].upper(),
                status=status,
                notes=fake.sentence() if random.random() > 0.5 else ''
            )

            if status == Donation.Status.CONFIRMED:
                donation.amount_confirmed = amount
                donation.reviewed_at = now - timedelta(days=days_ago - 1)
            elif status == Donation.Status.REJECTED:
                donation.admin_notes = "Payment could not be verified."
                donation.reviewed_at = now - timedelta(days=days_ago - 1)

            donation.save()
            
            # Retroactively update recorded_at if needed (auto_now_add makes it tricky on save)
            Donation.objects.filter(pk=donation.pk).update(
                recorded_at=now - timedelta(days=days_ago)
            )

        self.stdout.write(self.style.SUCCESS('[OK] Created 40 Fake Donations.'))

        # ---------------------------------------------------------------------
        # 3. Create Fake Expenditures (30)
        # ---------------------------------------------------------------------
        exp_categories = [c[0] for c in Expenditure.Category.choices]
        for _ in range(30):
            days_ago = random.randint(1, 365)
            exp_date = (now - timedelta(days=days_ago)).date()
            amount = round(random.uniform(10000, 2000000), 2)

            exp = Expenditure.objects.create(
                title=fake.catch_phrase(),
                amount=amount,
                date=exp_date,
                category=random.choice(exp_categories),
                notes=fake.sentence(),
                recorded_by="System Admin"
            )
            
            Expenditure.objects.filter(pk=exp.pk).update(
                created_at=now - timedelta(days=days_ago)
            )

        self.stdout.write(self.style.SUCCESS('[OK] Created 30 Fake Expenditures.'))

        # ---------------------------------------------------------------------
        # 4. Create Fake Scholarship Applications (20)
        # ---------------------------------------------------------------------
        levels = ['100 Level', '200 Level', '300 Level', '400 Level']
        for i in range(20):
            first = fake.first_name()
            last = fake.last_name()
            email = f"demo_applicant_{i}_{fake.email()}"

            user = CustomUser.objects.create_user(
                username=email,
                email=email,
                password='Password123!',
                first_name=first,
                last_name=last,
                role=CustomUser.Role.APPLICANT
            )

            rand_status = random.random()
            if rand_status < 0.25:
                status = ScholarshipApplication.Status.PENDING
            elif rand_status < 0.5:
                status = ScholarshipApplication.Status.UNDER_REVIEW
            elif rand_status < 0.75:
                status = ScholarshipApplication.Status.REJECTED
            else:
                status = ScholarshipApplication.Status.APPROVED

            app_days_ago = random.randint(30, 90)
            app = ScholarshipApplication.objects.create(
                applicant=user,
                academic_session='2024/2025',
                institution=fake.company() + ' University',
                course_of_study=fake.job(),
                level=random.choice(levels),
                current_cgpa=round(random.uniform(3.0, 5.0), 2),
                statement_of_purpose=fake.paragraph(nb_sentences=5),
                status=status,
                reviewer_notes="Looks promising." if status != ScholarshipApplication.Status.PENDING else ""
            )

            # Override application_date and created_at
            ScholarshipApplication.objects.filter(pk=app.pk).update(
                application_date=(now - timedelta(days=app_days_ago)).date(),
                created_at=now - timedelta(days=app_days_ago)
            )

            if status == ScholarshipApplication.Status.APPROVED:
                ScholarshipRecipient.objects.create(
                    application=app,
                    awarded_date=(now - timedelta(days=app_days_ago - 15)).date(),
                    amount_awarded=round(random.uniform(50000, 250000), 2),
                    notes="Approved by committee."
                )

        self.stdout.write(self.style.SUCCESS('[OK] Created 20 Fake Scholarship Applications.'))
        self.stdout.write(self.style.SUCCESS('[OK] Demo seed completed successfully! Dashboards are ready for presentation.'))
