# Generated by Django 6.0.6 on 2026-08-26 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, help_text='e.g. +234 801 234 5678', max_length=20, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, help_text='Street / city / state', verbose_name='Address')),
                ('notes', models.TextField(blank=True, help_text='Private notes visible only to Admins and Members.', verbose_name='Internal Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Donor',
                'verbose_name_plural': 'Donors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount (₦)')),
                ('date', models.DateField(verbose_name='Donation Date')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('online', 'Online Payment'), ('mobile_money', 'Mobile Money'), ('other', 'Other')], default='bank_transfer', max_length=20, verbose_name='Payment Method')),
                ('reference_number', models.CharField(blank=True, help_text='Bank teller number, transaction ID, cheque number, etc.', max_length=100, verbose_name='Reference / Receipt No.')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Recorded At')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donors.donor', verbose_name='Donor')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-date', '-recorded_at'],
            },
        ),
    ]
