# Generated by Django 6.0.6 on 2026-08-27 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Link to the CustomUser account for this donor. Leave blank for donors who do not use the portal.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Portal Login Account'),
        ),
    ]
