# Generated by Django 6.0.6 on 2026-08-27 03:52

import donors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_donor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Rejection reason or internal verification notes (visible to Donor).', verbose_name='Admin Notes'),
        ),
        migrations.AddField(
            model_name='donation',
            name='amount_confirmed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The amount the Admin verified actually hit the bank account.', max_digits=12, null=True, verbose_name='Amount Confirmed (₦)'),
        ),
        migrations.AddField(
            model_name='donation',
            name='receipt',
            field=models.FileField(blank=True, help_text='Upload a scan or photo of your bank receipt (PDF, PNG, JPG — max 5 MB).', null=True, upload_to=donors.models._donation_receipt_path, validators=[donors.models._validate_receipt_file], verbose_name='Payment Receipt'),
        ),
        migrations.AddField(
            model_name='donation',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At'),
        ),
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10, verbose_name='Verification Status'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='The amount the donor claims to have sent.', max_digits=12, verbose_name='Amount Claimed (₦)'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Donor Notes'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Submitted At'),
        ),
    ]
