# Generated by Django 6.0.6 on 2026-09-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_donation_admin_notes_donation_amount_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='admin_notes',
        ),
        migrations.AddField(
            model_name='donation',
            name='admin_note',
            field=models.TextField(blank=True, help_text='Reason for Not Confirmed or internal verification notes.', null=True, verbose_name='Admin Notes'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('not_confirmed', 'Not Confirmed')], db_index=True, default='pending', max_length=20, verbose_name='Verification Status'),
        ),
    ]
