# Generated by Django 6.0.6 on 2026-08-26 11:58

import expenditures.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief description of what this expenditure was for.', max_length=255, verbose_name='Title / Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount (₦)')),
                ('date', models.DateField(verbose_name='Expenditure Date')),
                ('category', models.CharField(choices=[('scholarship_grants', 'Scholarship Grants'), ('administrative', 'Administrative'), ('events', 'Events & Programs'), ('marketing', 'Marketing & Outreach'), ('logistics', 'Logistics & Transport'), ('other', 'Other')], default='other', max_length=30, verbose_name='Category')),
                ('receipt', models.FileField(blank=True, help_text='Upload a PDF, JPG, or PNG (max 5 MB).', null=True, upload_to=expenditures.models.receipt_upload_path, validators=[expenditures.models.validate_receipt_file], verbose_name='Receipt / Proof of Payment')),
                ('notes', models.TextField(blank=True, verbose_name='Additional Notes')),
                ('recorded_by', models.CharField(blank=True, help_text='Auto-filled from the logged-in user.', max_length=150, verbose_name='Recorded By')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Expenditure',
                'verbose_name_plural': 'Expenditures',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
