# Generated by Django 6.0.6 on 2026-08-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='requires_password_change',
            field=models.BooleanField(default=False, help_text='If True, user is redirected to change their password on next login. Set to True when an admin creates an account on behalf of a user.', verbose_name='Requires Password Change'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='unique_id',
            field=models.CharField(blank=True, help_text='System-assigned reference ID, e.g. KBD-0001 for donors, KBA-0001 for applicants. Auto-generated on save if blank.', max_length=20, null=True, unique=True, verbose_name='Unique Reference ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('reviewer', 'Reviewer'), ('applicant', 'Applicant'), ('donor', 'Donor')], default='applicant', help_text='Determines what areas of the system this user can access.', max_length=20),
        ),
    ]
