# Generated by Django 6.0.6 on 2026-09-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_requires_password_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='committee_role',
            field=models.CharField(choices=[('standard', 'Standard Member'), ('treasurer', 'Treasurer'), ('welfare', 'Welfare'), ('secretary', 'Secretary')], default='standard', help_text='Only applicable if the user is a Member.', max_length=20),
        ),
    ]
